swagger.yaml 피드백 요청
JEoN-Ha/Senior-Project pull request #76
Opened 2021-01-16 15:35 UTC by kiJiyeon

아름이가 보내준 `DB_WEB_정리.xlsx` 파일 참고해서 api 문서화 해봤음 더 필요한 내용이나 수정할 부분 알려조!

2021-01-16 15:44 UTC, kiJiyeon commented
잘,,,올린거 맞지...?

2021-01-17 03:30 UTC, fora22 requested changes
수정 부탁드립니다~

2021-01-17 03:30 UTC, fora22 commented on jiyeon/swagger.yaml
> +                type: object
- 저번에 Router 쪽에서 아이디랑 비번이 맞는지 아닌지 결정한다고 했으니까  `responses`는  성공 여부(에를 들어 true 혹은 false로, 아니면 0,1)를 응답해줘야될 것 같은데?

- 그리고 swagger 로 접속할 수 있는 URL은 혹시 없을까?

2021-01-17 03:30 UTC, fora22 commented on jiyeon/swagger.yaml
> +      resposes:
resposes -> responses 오타 발견

2021-01-17 03:30 UTC, fora22 commented on jiyeon/swagger.yaml
> +                type: object
여기도 회원가입 성공 여부만 반환해주면 될 듯
실패의 종류는 구분해야 함
- 비밀번호가 중복되었을 때의 경우
- 아이디가 중복되었을 경우
- 아이디 비밀번호가 너무 길어서 DB byte 수를 초과한 경우 -> DB에러

3가지 경우를 properties로 해놓고 description 에 설명해놓아야 함

2021-01-17 03:30 UTC, fora22 commented on jiyeon/swagger.yaml
> +      resposes:
resposes -> responses 오타 발견

2021-01-17 03:30 UTC, fora22 commented on jiyeon/swagger.yaml
> +                type: object
```yaml
 properties:
                  IdOverlap:
                    type: boolean
                  PwOverlap:
                    type: boolean
                  DbError:
                    type: boolean
```
혹은
```yaml
 properties:
                  logInFailed:
                    type: integer
```
이렇게 해서 0, 1, 2만 줘도 됨
- 대신 잘못된 로직으로 인해 3 이상의 수가 들어가면 대처하기 힘들고 
- description에 잘 설명해놓아야 함.

2021-01-17 03:55 UTC, fora22 requested changes
수정 부탁 2

2021-01-17 03:55 UTC, fora22 commented on jiyeon/swagger.yaml
> +      parameters:
내가 제대로 이해한게 맞는지는 모르겠는데 `get`은 원래 DB 내용을 read용으로 쓰는거니까 parameters 값이 필요한건가?

`fetch()`는 db로 보내는 data는 없는데 이게 swagger에서 필요한건지 아니면 작성하다가 넣어진건지 확인 바람!

2021-01-17 03:55 UTC, fora22 commented on jiyeon/swagger.yaml
> +          description: query successful !
`querry successful` 말고 어떤 api에서 무슨 쿼리를 하엿고 그게 성공했다는 식으로 쓰는게 좋아보임

모든 성공메시지가 동일함

2021-01-17 03:55 UTC, fora22 commented on jiyeon/swagger.yaml
> +          name: OrderToMenu_OrderNo
OrdreNo 는 client가 넣을 수 없음

https://github.com/JEoN-Ha/Senior-Project/blob/dcb166bdf5558af547db1cb8e4d8797b0c8b6485/fora22/DB/initDB.sql#L52-L65

order table 을 보면 OrdreNo가 AUTO_INCREMENT 임. 그래서 장바구니 넣을 때 OrderNo 가 자동으로 생긴 다음 ordertomenu table 에 넣어야 함

즉 순서가 (url은 가제임)
1. order table에 내용(아이디, 차량번호, 메뉴번호, 결제 방법 번호 등)을 넣음
2. order table의 OrderNo 를 가져옴(router에서 동작)
3. ordretomenu 테이블에 OrderNo를 넣음

**결론적으로 OrderNo 는 Client 가 알 수 없으니 Api 에 명세하면 안된다!**

2021-01-17 03:55 UTC, fora22 commented on jiyeon/swagger.yaml
> +          name: OrderState
https://github.com/JEoN-Ha/Senior-Project/blob/dcb166bdf5558af547db1cb8e4d8797b0c8b6485/fora22/DB/initDB.sql#L58

state 도 default 값이 정해져 있으므로 Server에 보낼 필요 없음!

2021-01-17 04:04 UTC, fora22 requested changes
수정 부탁 3

2021-01-17 04:04 UTC, fora22 commented on jiyeon/swagger.yaml
> +            type: integer
~OrderState 를 update 해줘야 되니(주문 전 -> 주문 후(수령전)) State update도 해야함~

`/order` 과 `/beforePaying`은 기능이 동일해보임. 통일하는 것이 좋아보임.

2021-01-17 04:04 UTC, fora22 commented on jiyeon/swagger.yaml
> +      parameters:
get 이므로 parameter 가 필요 없어 보임 
https://github.com/JEoN-Ha/Senior-Project/pull/76/files#r559072188

내 예상이 틀린 것 일 수도 있으니 의견 바람!

2021-01-17 04:13 UTC, fora22 commented on jiyeon/swagger.yaml
> +
주문 취소했을 때 혹은 장바구니 취소했을 때 fetch 도 만들어야 할 필요가 보임

2021-01-17 08:32 UTC, kiJiyeon commented on jiyeon/swagger.yaml
> +      parameters:
원래 `어떤 parameter들을 가져온다`라는 뜻으로 `parameter:`안에 필요한 것들 적어주는거라고 생각했었는데 아니었네!! 방금 테스트해보고 깨달았어 그냥 `responses:`안에만 넣어 주면 되는구낭!!

2021-01-17 08:45 UTC, kiJiyeon commented on jiyeon/swagger.yaml
> +            type: integer
오빠가 말한 `MenuNo`는
https://github.com/JEoN-Ha/Senior-Project/blob/7eccff4db11f10510d8368b9dad007ecb1fd0ab9/fora22/DB/initDB.sql#L23-L31
 
이 테이블에 있는 `MenuNo` 말하는거지??

2021-01-17 09:09 UTC, fora22 commented on jiyeon/swagger.yaml
> +            type: integer
아니아니 ordertomenu 테이블!

menuboard는 웹에서 건드릴 필요가 없음

2021-01-17 09:23 UTC, kiJiyeon commented on jiyeon/swagger.yaml
> +            type: integer
아 오케이 확인~

2021-01-17 09:26 UTC, kiJiyeon commented on jiyeon/swagger.yaml
> +      parameters:
윗 댓글 -> https://github.com/JEoN-Ha/Senior-Project/pull/76#discussion_r559097298 에서도 말했던내용이랑 같은의견 입니당~~~

2021-01-17 09:51 UTC, kiJiyeon commented
"장바구니 취소했을 때"는 사실 코멘트 달다가 생각났다,,,, 그것도 만들어서 다시 커밋할게!!

그리고 만든 api는 [SwaggerHub - kijiyeon-jeonha-redux](https://app.swaggerhub.com/apis/kiJiyeon/Jeonha-redux/1.0.0) 여기서도 확인가능~

2021-01-18 05:40 UTC, fora22 requested changes
2차 수정

2021-01-18 05:40 UTC, fora22 commented on jiyeon/jeonha_redux/public/swagger.yaml
> +    delete:
`delete` 말고 `post`로 변경 부탁

이유는 다음과 같음
- `cors()` 에러나 다른 것 때문에 복잡함
- 우리는 db에서 row 를 삭제할게 아니라 state 번호만 update 함

2021-01-18 05:40 UTC, fora22 commented on jiyeon/jeonha_redux/public/swagger.yaml
>            schema:
paying 을 하면 orderstate 가 update 되어야 하기 때문에 parameter 값이 있어야 함. 그게 빠진듯!

2021-01-18 07:53 UTC, kiJiyeon commented on jiyeon/jeonha_redux/public/swagger.yaml
>            schema:
orderState라는 parameter가 있어야한다는 말이야??

2021-01-18 07:57 UTC, kiJiyeon commented on jiyeon/jeonha_redux/public/swagger.yaml
> +    delete:
그럼 주문완료 된 상태에서 취소하는 것도 orderState 추가하고 post로 바꾸면 될까나?

2021-01-18 08:11 UTC, kiJiyeon commented on jiyeon/jeonha_redux/public/swagger.yaml
> +        #     type: integer
이부분 parameter를 `orderState`하나만 필요할 것 같아서 나머지 parameter들 다 주석처리해놨는데 어케 생각???

2021-01-18 11:38 UTC, fora22 commented on jiyeon/jeonha_redux/public/swagger.yaml
> +        #     type: integer
지우는 것과 비교했을 때 이유가 있다면 괜찮다고 생각함!

지우지 않는 이유가 혹시 있음??

2021-01-18 11:41 UTC, kiJiyeon commented on jiyeon/jeonha_redux/public/swagger.yaml
> +        #     type: integer
지우지 않는 이유는 **논의전이라 호옥시나 해서 남겨둔거**고, OrderState만 필요할것 같다고 생각한 이유는 update되는 parameter가 OrderState이기 때문!

2021-01-18 11:53 UTC, fora22 commented on jiyeon/jeonha_redux/public/swagger.yaml
>            schema:
ㅇㅇㅇ 필요하지 않나?

그냥  router 에서 Update 하게 할까?

2021-01-18 11:55 UTC, kiJiyeon commented on jiyeon/jeonha_redux/public/swagger.yaml
>            schema:
위에 이미 있는거 아녀!? 226,227라인?

2021-01-18 11:59 UTC, fora22 commented on jiyeon/jeonha_redux/public/swagger.yaml
> +        #     type: integer
https://github.com/JEoN-Ha/Senior-Project/pull/76/files/1f7e85ecf3d7d60ee33be605fb6a11520d15a1d5#r559513851

주석은 괜찮은데 일단 이야기해야할 게 2가지 있음! 일단 OrderState같은 경우에는 사실 Update 경우가 정해져 있잖아?

`장바구니 내역 삭제`랑 `결제 취소`이면 Post로 parameter 를 보낼게 아니라 그냥 router 에서 update 를 해줘도 상관 없어 보임! (왜냐하면 deleteBastket 은 OrdreState 가 Update 되면 되니까) -> **즉 Parameter 로 OrderState를 보내주지 않아도 됨**

두번 째는 서버입장에서는 어느 주문을 주문 취소해야할지 모름! 그래서 어떤 주문을 취소해야할지 구분할 수 있는 OrderNo 가 필요함.
하지만 OrderNo는 `AUTO_INCREMENT`라서 Client는 기본적으로 값을 모름!

즉  Client가 OrderNo에 대한 값을 가지고 있어야할 것으로 보임!

2021-01-18 12:06 UTC, kiJiyeon commented on jiyeon/jeonha_redux/public/swagger.yaml
> +        #     type: integer
- [ ] 첫번째 말은 parameter에 orderState를 넣어줄 필요가 없다는거지??

- [ ] 근데 두번째 말에서 `Client가 OrderNo에 대한 값을 가지고 있어야` 하는거면 `get`으로 OrderNo를 가져오면 되는건가?? 

내가 이해한게 맞아!? (맞으면 체크 틀리면 코멘트를 달아주세요)

2021-01-18 13:32 UTC, fora22 commented on jiyeon/jeonha_redux/public/swagger.yaml
> +        #     type: integer
> * 첫번째 말은 parameter에 orderState를 넣어줄 필요가 없다는거지??

넣어도 되고 안넣어도 될 것 같지만, 안넣었을때의 문제점이 어떤 것이 있을까 싶어서 한 말이였음!

> * [ ]  근데 두번째 말에서 `Client가 OrderNo에 대한 값을 가지고 있어야` 하는거면 `get`으로 OrderNo를 가져오면 되는건가??

가져와서 OrderNo 를 Front 쪽에서 가지고 있어야 하지 않을까 싶어서! 이건 이야기를 좀 해봐야 할 것 같아. 나도 머릿속에서 정리가 잘 안되네!

> 내가 이해한게 맞아!? (맞으면 체크 틀리면 코멘트를 달아주세요)

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2021-01-18 13:33 UTC, fora22 commented on jiyeon/jeonha_redux/public/swagger.yaml
>            schema:
OrderState 이야기가 요기로 넘어감 -> https://github.com/JEoN-Ha/Senior-Project/pull/76/files#r559517027

2021-01-18 14:29 UTC, kiJiyeon commented on jiyeon/jeonha_redux/public/swagger.yaml
> +                    type: integer
/CancelOrder/{userWebId}로 해서 특정user의 Orderstate만 get해와서 Post하는건 ?? 음,,,코멘트 쓰다가도 헷갈리네
@fora22

2021-01-19 08:24 UTC, fora22 commented on jiyeon/jeonha_redux/public/swagger.yaml
> +                    type: integer
일단 그렇게 할려면 `get`이 아니라 `post`로 해야할 것 같고! (왜냐하면 UserWebId를 보내야 하니까!) 말해준 방식으로 하면
## CancelOrder의 경우
1. OrderState가 2(결제 후)이고 UserWebId가 동일한 OrderNo를 가져온다.
2. 해당 OrderNo의 OrderState를 5(주문 취소)로 바꾼다.

## Cancel_Insert_Basket의 경우
1. OrderState가 1(결제 전)이고 UserWebId가 동일한 OrderNo를 가져온다.
2. 해당 OrderNo의 OrderState를 4(장바구니 취소)로 바꾼다.

이렇게 해야할 듯??

2021-01-19 08:42 UTC, kiJiyeon commented on jiyeon/jeonha_redux/public/swagger.yaml
> +                    type: integer
1.  이 바로 밑부분에 post도 있는데 그냥 get  자체를 쓰지말고 post로만 쓰자는것??
 2. 
> ## CancelOrder의 경우
> 1. OrderState가 2(결제 후)이고 UserWebId가 동일한 OrderNo를 가져온다.
> 2. 해당 OrderNo의 OrderState를 5(주문 취소)로 바꾼다.
> 
> ## Cancel_Insert_Basket의 경우
> 1. OrderState가 1(결제 전)이고 UserWebId가 동일한 OrderNo를 가져온다.
> 2. 해당 OrderNo의 OrderState를 4(장바구니 취소)로 바꾼다.
> 
사실 이부분이 작성한 거랑 뭐가 다른지 잘 모르겠음!!!!

2021-01-19 11:13 UTC, fora22 commented on jiyeon/jeonha_redux/public/swagger.yaml
> +                    type: integer
post가 데이터를 읽어오는 것도 가능함!

즉 get은 read만 가능하고 post 는 데이터 보내기(Update, Insert)  + 읽기(select)도 가능함!

즉 get하고 post는 따로 적을 필요가 없음!

그리고 한 URL에 두개 동시에 동작 못하는걸로 알고있음(`/CancelOrder/{UserWebId}`에 get, post 중 하나만 사용해야함)

2021-01-19 15:10 UTC, fora22 commented on jiyeon/jeonha_redux/public/swagger.yaml
> +      parameters:
장바구니 삭제에서는 UserWebId, MenuNo 가 필요함

2021-01-19 15:11 UTC, fora22 commented on jiyeon/jeonha_redux/public/swagger.yaml
> +                    type: integer
주문취소에서는  UserWebId만 보내주면 됨!

2021-01-21 09:23 UTC, fora22 commented on jiyeon/jeonha_redux/public/swagger.yaml
> +                    type: boolean
얼추 된 듯? 이 파일이 완성본인가??

2021-01-21 11:44 UTC, kiJiyeon commented on jiyeon/jeonha_redux/public/swagger.yaml
> +                    type: boolean
어어 이 파일이 완성본임!

2021-01-24 14:44 UTC, fora22 approved these changes

2021-01-24 14:45 UTC, merged